Apt 278 fix double satisfaction vul
aadafinance/aada-finance pull request #31
Opened 2022-08-08 14:05 UTC by tomazvila

2022-08-12 10:38 UTC, tomazvila commented
Once https://github.com/aadafinance/aada-finance/pull/32 gets merged this needs similar change as https://github.com/aadafinance/aada-finance/commit/07c4f47a6fd4f2b5b565943141e0648b53bbfbad

2022-08-12 10:48 UTC, mikx98 requested changes

2022-08-12 10:48 UTC, mikx98 commented on src/Request.hs
> +    borrowerGetsWhatHeWants = assetClassValueOf valueToBorrower (loan dat) >= loanamnt dat && assetClassValueOf valueToBorrower (loan dat) >= assetClassValueOf (U.valueIn ctx) (loan dat)
I think this doesn't do the job for every possible loan asset class. For simplicity, let's just imagine loan currency being ADA. You can't require all ADA from all inputs being given to borrower. Aside from paying for tx fees, you also need to insert min-ADA amount to the ongoing Collateral script.

I would suggest explicitly checking that no other script input is present in the transaction (ideally, all transactions).

2022-08-15 10:41 UTC, cptmikx approved these changes

2022-08-15 13:43 UTC, merged